services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/btp_tokens?sslmode=disable
      - PORT=8080
  db:
    image: postgres:16-alpine
    container_name: btp_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=btp_tokens
    volumes:
      # To prevent erasing data after continer restart
      - postgres_data:/var/lib/postgresql/data
      # To initial tables
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./init.sql:/docker-entrypoint-initdb.d/02_init.sql

volumes:
  postgres_data: